// import Navbar from "../../components/Navbar";


// export default function Home() {
//   return (
//    <>
//    <Navbar />
//    </>
//   )
// }
import Head from "next/head";
import HeroSection from "components/HeroSection";
import Navbar from "/components/Navbar";
import Footer from "../../components/Footer";
export default function Home() {
	return (
		<>
		<div>
			{/* <Head>
				<title>Navigation using nextjs and tailwindcss</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<Navbar />
			<HeroSection />
			<Footer/> */}
			<h1>HIIII</h1>
		</div>
		</>
	);
};